#!/bin/sh

set -e
set -u

. /usr/lib/i2p/i2p.sh

I2P_STARTUP_TIMEOUT=60
I2P_BOOTSTRAP_TIMEOUT=210
I2P_TUNNEL_BUILD_TIMEOUT=450

startup_failure() {
    notify-send -t 5000 "I2P failed to start \nSomething went wrong when I2P was starting. Check the logs in /var/log/i2p/ for more information."
    service i2p dump # generate a thread dump
    sleep 5 # Give thread dump ample time to complete
    systemctl stop i2p # clean up, just in case
    exit 1
}

wait_until_i2p_router_console_is_ready() {
    wait_until ${I2P_STARTUP_TIMEOUT} i2p_router_console_is_ready
}

wait_until_i2p_has_bootstrapped() {
    wait_until ${I2P_BOOTSTRAP_TIMEOUT} '[ "$(i2p_reseed_status)" = success ]'
    notify-send -i /usr/share/icons/anon-icon-pack/i2p-con.png -t 5000 "I2P's Reseeding was successful "

}

notify_router_console_success() {
    notify-send -i /usr/share/icons/anon-icon-pack/i2p-con.png -t 5000 "I2P's router console is ready" "You can now access I2P's router console"
    
}

bootstrap_failure() {
    notify-send -t 5000 "I2P is not ready" "Eepsite tunnel not built within six minutes. Check the router console in the Tor Browser or the logs in /var/log/i2p for more information. Reconnect to the network to try again."
    exit 1
}

wait_until_i2p_builds_a_tunnel() {
    wait_until ${I2P_TUNNEL_BUILD_TIMEOUT} i2p_built_a_tunnel
    sleep 240
    notify-send -i /usr/share/icons/anon-icon-pack/i2p-con.png -t 5000 "I2P build a tunnel" "I2P has successfully built a tunnel"
}

notify_bootstrap_success() {
    notify-send -i /usr/share/icons/anon-icon-pack/i2p-ready.png -t 5000 "I2P is ready" "You can now access services on I2P"

}

case "${1}" in
    start|restart)
        if systemctl --quiet is-active i2p; then
            systemctl stop i2p
        fi

        systemctl start i2p 
        tail /var/log/i2p/wrapper.log
        notify-send -i /usr/share/icons/anon-icon-pack/i2p-start.png -t 4000 "I2P's router is starting" 
        wait_until_i2p_router_console_is_ready || startup_failure
        notify_router_console_success
	iceweasel 127.0.0.1:7657
        wait_until_i2p_has_bootstrapped || bootstrap_failure
        wait_until_i2p_builds_a_tunnel || bootstrap_failure
        notify_bootstrap_success
        ;;
    stop)
        exec systemctl stop i2p
        notify-send -i /usr/share/icons/anon-icon-pack/i2p-start.png -t 4000 "I2P's router is Shutting down" 
        ;;
    *)
        echo "invalid argument '${1}'" >&2
        exit 1
        ;;
esac
